### ISSUE TITLE
Can not find DiagonalLoss ?

### ISSUE THREAD

**Issue by ghost** [kissb2/PyICP-SLAM#3]
Hi @kissb2 I have run PyICP-SLAM but after installing minisam, I ran into a problem that is:
AttributeError: module 'minisam' has no attribute 'DiagonalLoss
I have built successfully like the guidance in the minisam repo. Could you help me, please ?

**Comment by XMU-qcj** [comment]
> Hi @kissb2 I have run PyICP-SLAM but after installing minisam, I ran into a problem that is: AttributeError: module 'minisam' has no attribute 'DiagonalLoss I have built successfully like the guidance in the minisam repo. Could you help me, please ?

I'm sorry to bother you, I would like to ask you if this problem has been solved?

**Comment by Shubham-2302** [comment]
Hello @ngthanhtin @Unknownnnnnnn .
Were any of you able to solve this? Can you explain how did you solve this error?
