### ISSUE TITLE
Question about the generated .csv file

### ISSUE THREAD

**Issue by mengqingyu123** [kissb2/PyICP-SLAM#4]
First of all, thank you very much for your excellent work. When I use the code to run the kitti dataset, there will be multiple .csv files in the result folder after running a sequence every time. Why is this? In other words, I want to compare the saved pose with groundtruth, but the multiple files generated make me a little confused.
Thanks again!

**Comment by Shubham-2302** [comment]
Hey @mengqingyu123  I am also in the same situation. Were you able to compare it with the ground truth?
