### ISSUE TITLE
Have a question on a 4x4 matrix parameter in UtilsMisc.py 

### ISSUE THREAD

**Issue by narwhal93** [kissb2/PyICP-SLAM#5]
Hi, im working on a project having registration with only depth images.

Im now trying to understand and modifying to do a job, and I got a simple question on your code in line 64, UtilsMisc.py.

Why did you put 0.1 instead of 1 in the  optimized_pos_ith 4x4 matrix. I know there's no difference in the result, but I just wanna know the reason, if there a benefit from it or not.

**Comment by gisbi-kim** [comment]
@narwhal93 hi, thanks for having an interest in the work. 
I think it was a typo. Thanks for the finding and I'll fix it :)

**Comment by narwhal93** [comment]
@gisbi-kim thx for answer it:)))
